#!/usr/bin/env bash
# Script to copy file to remote host

if [ $# -lt 4 ]; then
	echo -e "Usage: 0-transfer_file PATH_TO_FILE IP" \
		"USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi
