#!/usr/bin/env bash
# Script to install and start nginx web server

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo 'echo "Hello World!" | sudo tee /var/www/html/index.html'
sudo service nginx restart
