#!/usr/bin/env bash
# Script to install and start nginx web server

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo sh -c 'echo "Hello World!"  > /usr/share/nginx/html/index.html'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx restart
