#!/usr/bin/env bash
# Script to configure site redirection in nginx

pattern="server_name _;"
replacement="server_name _;\n\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
file="/etc/nginx/sites-available/default"

sudo sed -i "s@$pattern@$replacement@g" $file
sudo systemctl restart nginx
