#!/usr/bin/env bash
# Script to create a custom webpage

pattern="^\tlocation / {"
replacement="\terror_page 404 /404.html;\
	location = /404.html {\
		root /usr/share/nginx/html;\
		internal;\
	}\n\n\
	location / {"
file="/etc/nginx/sites-available/default"

sudo apt -y update
sudo apt -y upgrade
sudo apt install -y nginx
sudo sh -c 'echo -e "Ceci n'\''est pas une page" > /usr/share/nginx/html/404.html'
sudo sed -iE "s@$pattern@$replacement@g" $file
sudo service nginx restart
