#!/usr/bin/env bash
# Script to install nginx server and configure custom header
# shellchek disable=SC2154
# shellcheck disable=SC2016

custom_header='http {\
	add_header X-Served-By \$HOSTNAME;'
file='/etc/nginx/nginx.conf'

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo sed -i s@'http {'@"$custom_header"@g "$file"
sudo service nginx restart
