#!/usr/bin/env bash
# Script to install nginx server and configure custom header

# shellcheck disable=SC2016 # variable expansion is will be done by nginx

pattern='server_name _;'
replacement='server_name _\
	add-header X-Served-By $hostname;'
file='/etc/nginx/sites-available/default'

sudo apt -y update
sudo apt -y install nginx
sudo sed -i s/"$pattern"/"$replacement" "$file"
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx restart
