#!/usr/bin/env bash
# Script to install and setup HAProxy load balancer for two web servers

sudo apt -y update
sudo apt -y upgrade
sudo apt -y --no-install-recommends software-properies-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt install haproxy=2.0.\*
