#!/usr/bin/env bash
# Script that manages the execution of manage_my_process script
# Syntax: manage_my_process [start|stop|restart]
# Option:
# 	start: start the script
#	stop: stop the script
#	restart: restart the script

function error()
{
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
}

function start()
{
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
}

function stop()
{
	echo "manage_my_process stopped"
	kill "$(cat /run/my_process.pid)"
	rm /run/my_process.pid
}

function restart()
{
	kill "$(cat /run/my_process.pid)"
	rm /run/my_process.pid
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
}

if [ "$#" -lt 1 ]; then
	"error"
elif [ "$1" = "start" ]; then
	"start"
elif [ "$1" = "restart" ]; then
	"restart"
elif [ "$1" = "stop" ]; then
	"stop"
else
	"error"
fi
