#!/usr/bin/env bash
# Script to print numbers 1 - 10 and:
# 	'bad luck' at 4th iteration
#	'good luck' at 8th iteration

a=0
while [[ "$a" -lt 10 ]]
do
	if [ "$a" -eq 3 ]; then
		echo "bad luck"
	elif [ "$a" -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((a = "$a" + 1))
done
