#!/usr/bin/env bash
# Script to print numbers from 1 to 20 and
# 	'bad luck from China at 4th iteration'
# 	'good luck from Japan at 9th iteration'
# 	'bad luck from Italy at 17th iteration'

a=1
while [ "$a" -lt 20 ] || [ "$a" -eq 20 ]
do
	echo "$a"
	case "$a" in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	((a = "$a" + 1))
done
