#!/usr/bin/env bash
# Script that displays time for 12 hours and 59 minutes

hr=-1
min=59

while [ "$hr" -lt 13 ]
do
	if [ "$min" -eq 59 ]; then
		((hr += 1))
		if [ "$hr" -ne 0 ]; then
			echo "$min"
		fi
		if [ $hr -ne 13 ]; then
			echo "Hour: $hr"
		fi
		((min = 1))
		continue
	else
		echo "$min"
		((min += 1))
	fi
done 
