#!/usr/bin/env bash
# Alternate script for 1--run_nginx_as_nginx script
pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i s/'80 default_server'/'8080 default_server'/g /etc/nginx/sites-available/default
sudo -u nginx service nginx start
